### ISSUE TITLE
Building Error

### ISSUE THREAD

**Issue by idkjs** [charlesetc/Orb#1]
Hi. Thanks for sharing this. As an avid code reader, I am glad to have found your repositories.

I tried building this unsuccessfully. Maybe you can help me out if you get a second.

Here is the error I am getting. Tried on 4.10.0 and 4.07.1 figureing the ppx needed it. Same result:

```sh

dune build ppx/classic/ppx_orb_classic.exe
File "ppx/ppx_orb.ml", line 11, characters 11-36:
11 |       Some [%expr Orb.int [%e expr]]
                ^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Unbound record field pexp_loc_stack
Done: 13/17 (jobs: 1)make: *** [top] Error 1
```

Ideas?

**Comment by charlesetc** [comment]
Thanks for letting me know! I'm not planning on putting the work into fix it but I updated the readme. Happy reading!
